Repository optimizely/ruby-sdk, pull requests merged in 2020-05, with the labels that each got.

#248 handle error with error handler in async scheduler
  lib/optimizely/config_manager/async_scheduler.rb
  spec/config_manager/async_scheduler_spec.rb
Labels: :robot: 20 hrs

#249 refact: avoid real http calls in unit tests
  spec/project_spec.rb
Labels: :robot: 24 hrs

#251 feat: Added new getFeatureVariableJson and getAllFeatureVariables Apis
  lib/optimizely.rb
  lib/optimizely/config/datafile_project_config.rb
  lib/optimizely/helpers/constants.rb
  lib/optimizely/helpers/variable_type.rb
  spec/config/datafile_project_config_spec.rb
  spec/optimizely_config_spec.rb
  spec/project_spec.rb
  spec/spec_params.rb
Labels: :robot: 4 hrs

#250 fix: errors being raised without required args
  lib/optimizely/config/datafile_project_config.rb
  lib/optimizely/config_manager/http_project_config_manager.rb
  lib/optimizely/exceptions.rb
  spec/config_manager/http_project_config_manager_spec.rb
  spec/project_spec.rb
Labels: :robot: 24 hrs

#252 refact: Replace httparty in favor of core net/http package
  .gitignore
  lib/optimizely/config_manager/http_project_config_manager.rb
  lib/optimizely/event_dispatcher.rb
  lib/optimizely/helpers/http_utils.rb
  optimizely-sdk.gemspec
  spec/config_manager/http_project_config_manager_spec.rb
  spec/event_dispatcher_spec.rb
Labels: :robot: 24 hrs
